debug: false
server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
            - Method=GET,POST
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/v1/items/**
            - Method=GET,POST
